"""Static coffee menu data for the local recommendation demo."""

COFFEE_MENU = [
    {
        "id": "espresso",
        "name": "Espresso",
        "style": "hot",
        "milk": False,
        "caffeine": "high",
        "flavor_notes": ["bold", "bitter", "concentrated"],
        "best_for": ["quick energy", "classic coffee flavor"],
        "description": "A short, concentrated coffee with a bold profile.",
    },
    {
        "id": "americano",
        "name": "Americano",
        "style": "hot",
        "milk": False,
        "caffeine": "medium",
        "flavor_notes": ["smooth", "clean", "balanced"],
        "best_for": ["black coffee", "longer sipping"],
        "description": "Espresso diluted with hot water for a clean black coffee.",
    },
    {
        "id": "latte",
        "name": "Latte",
        "style": "hot",
        "milk": True,
        "caffeine": "medium",
        "flavor_notes": ["creamy", "mild", "soft"],
        "best_for": ["milk coffee", "gentle flavor"],
        "description": "Espresso with steamed milk and a small layer of foam.",
    },
    {
        "id": "cappuccino",
        "name": "Cappuccino",
        "style": "hot",
        "milk": True,
        "caffeine": "medium",
        "flavor_notes": ["foamy", "balanced", "toasty"],
        "best_for": ["milk coffee", "stronger texture"],
        "description": "Espresso with steamed milk and a thicker foam cap.",
    },
    {
        "id": "flat_white",
        "name": "Flat White",
        "style": "hot",
        "milk": True,
        "caffeine": "high",
        "flavor_notes": ["velvety", "rich", "espresso-forward"],
        "best_for": ["strong milk coffee", "smooth texture"],
        "description": "A compact milk coffee with a rich espresso base.",
    },
    {
        "id": "cold_brew",
        "name": "Cold Brew",
        "style": "cold",
        "milk": False,
        "caffeine": "high",
        "flavor_notes": ["smooth", "low-acid", "chocolatey"],
        "best_for": ["iced coffee", "slow sipping"],
        "description": "Coffee brewed cold for a smooth, less acidic cup.",
    },
    {
        "id": "iced_latte",
        "name": "Iced Latte",
        "style": "cold",
        "milk": True,
        "caffeine": "medium",
        "flavor_notes": ["creamy", "refreshing", "mild"],
        "best_for": ["iced milk coffee", "warm days"],
        "description": "Espresso and milk served over ice.",
    },
    {
        "id": "mocha",
        "name": "Mocha",
        "style": "hot",
        "milk": True,
        "caffeine": "medium",
        "flavor_notes": ["chocolatey", "sweet", "creamy"],
        "best_for": ["dessert-like coffee", "sweet cravings"],
        "description": "Espresso, milk, and chocolate for a sweeter coffee.",
    },
    {
        "id": "decaf_latte",
        "name": "Decaf Latte",
        "style": "hot",
        "milk": True,
        "caffeine": "low",
        "flavor_notes": ["creamy", "mild", "soft"],
        "best_for": ["low caffeine", "evening coffee"],
        "description": "A latte made with decaf espresso.",
    },
]
